// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk26C3oNb2k0FI_JrxiwIVnI_wIMVkCmE',
    appId: '1:960850992242:web:aed798bfbc1270e39436eb',
    messagingSenderId: '960850992242',
    projectId: 'iagp-app',
    authDomain: 'iagp-app.firebaseapp.com',
    storageBucket: 'iagp-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVidbFeE8FeqZVrd1E8wbBPaV-Pb8HOJI',
    appId: '1:960850992242:android:b351f11002a103069436eb',
    messagingSenderId: '960850992242',
    projectId: 'iagp-app',
    storageBucket: 'iagp-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcG2OUFVU0KbRMk3Up9lxo34SNLAgsrcw',
    appId: '1:960850992242:ios:2bf2483eb7df25cf9436eb',
    messagingSenderId: '960850992242',
    projectId: 'iagp-app',
    storageBucket: 'iagp-app.firebasestorage.app',
    iosBundleId: 'br.com.iagp.app.iagpApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcG2OUFVU0KbRMk3Up9lxo34SNLAgsrcw',
    appId: '1:960850992242:ios:2bf2483eb7df25cf9436eb',
    messagingSenderId: '960850992242',
    projectId: 'iagp-app',
    storageBucket: 'iagp-app.firebasestorage.app',
    iosBundleId: 'br.com.iagp.app.iagpApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk26C3oNb2k0FI_JrxiwIVnI_wIMVkCmE',
    appId: '1:960850992242:web:3d929227c5f7784a9436eb',
    messagingSenderId: '960850992242',
    projectId: 'iagp-app',
    authDomain: 'iagp-app.firebaseapp.com',
    storageBucket: 'iagp-app.firebasestorage.app',
  );
}
