name: 🔥 Firebase Deploy (Firestore Indexes + Rules)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Firebase Config
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout código
        uses: actions/checkout@v3

      - name: 🔧 Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: 🔑 Autenticar com Firebase
        run: firebase deploy --only firestore:indexes,firestore:rules --token ${{ secrets.FIREBASE_TOKEN }}
